cluster:
  mkdir -p {params.logdir}/{rule} &&
  sbatch
    --job-name {rule}
    --partition {params.partition}
    --mem 50G
    --output {params.logdir}/{rule}/{params.job_label}_{params.jobid}.out
jobs: 10
use-conda: true
restart-times: 1
printshellcmds: True
cores: 1
latency-wait: 60 

